PrimerMVCNetCore/Models/ErrorViewModel.cs
namespace PrimerMVCNetCore.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PrimerMVCNetCore/Models/Persona.cs
namespace PrimerMVCNetCore.Models
{
    public class Persona
    {
        public string Nombre { get; set; }
        public string Email { get; set; }
        public int Edad { get; set; }

    }
}

PrimerMVCNetCore/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PrimerMVCNetCore.Models;

namespace PrimerMVCNetCore.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PrimerMVCNetCore/Controllers/InformacionController.cs
using Microsoft.AspNetCore.Mvc;
using PrimerMVCNetCore.Models;

namespace PrimerMVCNetCore.Controllers
{
    public class InformacionController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult VistaControllerPost()
        {
            return View();
        }

        //[HttpPost]
        public IActionResult VistaControllerPost(Persona persona, string aficiones)
        {
            ViewData["Mensaje"] = "Nombre " + persona.Nombre + ", Email " + persona.Email + ", Edad " + persona.Edad + " y además " + aficiones;
            return View();
        }

        public IActionResult VistaControladorGet(string saludo, int? year)
        {
            //para comprobar que hemos recibido los datos mediante un IActionLink
            //devolvemos un mensaje a la vista
            if (year == null)
            {
                ViewData["Mensaje"] = "Que year es?????";
            }
            else if (saludo == null)
            {
                ViewData["Mensaje"] = "Aqui nadie saluda...";
            }
            else
            {
                ViewData["Mensaje"] = saludo + " en el año " + year;
            }
            return View();
        }

        public IActionResult ControladorVista()
        {
            //vamos a enviar informacion simple a nuestra vista
            ViewData["Nombre"] = "Alumno";
            ViewData["Edad"] = "20";
            ViewBag.DiaSemana = "Jueves";
            return View();
        }

        public IActionResult ControladorVistaModel()
        {
            Persona persona = new Persona();
            persona.Nombre = "Alumno";
            persona.Email = "alumno@gmail.com";
            persona.Edad = 20;

            return View(persona);
        }
    }
}

PrimerMVCNetCore/Controllers/PruebaController.cs
using Microsoft.AspNetCore.Mvc;

namespace PrimerMVCNetCore.Controllers
{
    public class PruebaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PrimeraPagina()
        {
            return View();
        }
    }
}

PrimerMVCNetCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <a asp-controller="Prueba" asp-action="PrimeraPagina">Navegar a primera pagina</a>
    <a asp-controller="Prueba" asp-action="Test">Navegar a test</a>
    <a asp-controller="Prueba" asp-action="Index">Razor</a>
</div>

PrimerMVCNetCore/Views/Informacion/ControladorVista.cshtml
<h1>Informacion controller --> View</h1>
<h2>Nombre: @ViewData["Nombre"]</h2>
<h2>Edad: @ViewData["Edad"]</h2>
<h2>Hoy es ... @ViewBag.DiaSemana</h2>

PrimerMVCNetCore/Views/Informacion/ControladorVistaModel.cshtml
@model Persona

<h1>Controlador --> View --> Model</h1>

@if (Model != null)
{
    <h2>@Model.Nombre, @Model.Email, @Model.Edad</h2>
}
else
{
    <h2>No he recibido el Model</h2>
}

PrimerMVCNetCore/Views/Informacion/Index.cshtml
<h1>Menu informacion</h1>
<ul>
    <li>
        <a asp-controller="Informacion" asp-action="ControladorVista">Controlador --> Vista</a>
    </li>
    <li>
        <a asp-controller="Informacion" asp-action="ControladorVistaModel">Controlador --> Vista  --> Model</a>
    </li>
    <li>
        @Html.ActionLink("Vista Controlador GET sin saludo", "VistaControladorGet", "Informacion", 
                        new {/* saludo = "Hola carcaola", */ year = 2026})
    </li>
    <li>
        @Html.ActionLink("Vista Controlador GET sin year", "VistaControladorGet", "Informacion",
                new {saludo = "Hola carcaola"/* , year = 2026 */ })
    </li>
    <li>
        @Html.ActionLink("Vista Controlador GET OKK", "VistaControladorGet", "Informacion",
                new { saludo = "Hola carcaola", year = 2026 })
    </li>
    <li>
        <a asp-controller="Informacion" asp-action="VistaControllerPost">Vista Controller Post</a>
    </li>
</ul>

PrimerMVCNetCore/Views/Informacion/VistaControladorGet.cshtml
<h1>Vista Controlador GET</h1>
<h2>@ViewData["Mensaje"]</h2>

PrimerMVCNetCore/Views/Informacion/VistaControllerPost.cshtml
<h1>Vista Controller Post</h1>

<form method="post">
    <label>Nombre</label>
    <input type="text" name="nombre" class="form-control"/>
    <label>Email</label>
    <input type="text" name="email" class="form-control" />
    <label>Edad</label>
    <input type="text" name="edad" class="form-control" />
    <label>Aficiones</label>
    <input type="text" name="aficiones" class="form-control" />
    <button class="btn btn-info">Enviar datos</button>
</form>

<h2>@ViewData["Mensaje"]</h2>

PrimerMVCNetCore/Views/Prueba/Index.cshtml
@*
    Comentario razor
*@

<h1>Codigo razor</h1>

@{
    //codigo c#
    int valor = 1;
    string dato = "Hoy es jueves";

    valor += 1;
    dato += " y mañana viernes de examen";
}

<h2>Variables: @dato y @valor</h2>

@if (valor > 0)
{
    //codigo c#
    dato = "POSITIVO";
    <h3>El num es positivo</h3>
}
else
{
    dato = "NEGATIVO";
    <h3>El num es negativo</h3>
}

@dato

PrimerMVCNetCore/Views/Prueba/PrimeraPagina.cshtml
<h1>Hola soy la primera pagina :)</h1>

PrimerMVCNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrimerMVCNetCore</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PrimerMVCNetCore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PrimerMVCNetCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Prueba" asp-action="PrimeraPagina">Primera pagina</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Informacion" asp-action="Index">Informacion</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - PrimerMVCNetCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>